#!/bin/bash

DIR=$HOME/.config/hypr/bg
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

if [[ $(pidof swaybg) ]]; then
	pkill swaybg
fi

#!/usr/bin/bash

# Check if URL argument is provided
if [ -z "$1" ]; then
	echo "Error: Please provide a URL as an argument."
	exit 1
fi

# Create pictures directory if it doesn't exist
mkdir -p ~/Pictures

# Download the image
curl -o ~/Pictures/wallpaper.jpg "$1"

# Check if the download was successful
if [ $? -eq 0 ]; then
	echo "Image downloaded successfully and stored as ~/pictures/wallpaper.jpg"

	# swaybg -m fill -i ${DIR}/${RANDOMPICS}
	swaybg -m fill -i ~/Pictures/wallpaper.jpg
	# notify-send "${RANDOMPICS}"
else
	echo "Error: Failed to download the image."
fi
