#!/bin/bash

set_wallpaper() {
	echo 'changing'
	swaybg -m fill -i ~/Pictures/wallpaper >/dev/null 2>&1 &
}

set_wallpaper

# Check if URL argument is provided
if [ -z "$1" ]; then
	echo "Error: Please provide a URL as an argument."
	echo "Using the current wallpaper"
	wal -c && wal -i ~/Pictures/wallpaper
	exit 1
fi

# Create pictures directory if it doesn't exist
mkdir -p ~/Pictures

# Download the image
curl -o ~/Pictures/wallpaper "$1"

# Check if the download was successful
if [ $? -eq 0 ]; then
	echo "Image downloaded successfully and stored as ~/pictures/wallpaper.jpg"

	# swaybg -m fill -i ${DIR}/${RANDOMPICS}
	# swaybg -m fill -i ~/Pictures/wallpaper >/dev/null 2>&1 &
	set_wallpaper
	echo "Wallpaper is changed"
	wal -c && wal -i ~/Pictures/wallpaper
	# notify-send "${RANDOMPICS}"
else
	echo "Error: Failed to download the image."
fi
