#!/bin/bash

case $1 in
"--win")
	rofi -show window
	;;
"--emoji")
	rofi -show emoji
	;;
"--clip")
	rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
	;;
*)
	rofi -show drun
	;;

esac
